// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTQLAR7-Wtksfj0sPTx3oSvjBXkHcooA',
    appId: '1:260233386063:web:0ac5582c21db6ab3d6323a',
    messagingSenderId: '260233386063',
    projectId: 'avi-care',
    authDomain: 'avi-care.firebaseapp.com',
    storageBucket: 'avi-care.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzY-FM0XNLUG2GklNvUZPMG5MVqvZzE8',
    appId: '1:260233386063:android:6c782a4905e0ee30d6323a',
    messagingSenderId: '260233386063',
    projectId: 'avi-care',
    storageBucket: 'avi-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87_NBzLeMvm0FZTQPZjUJ-BYYOsbYzSo',
    appId: '1:260233386063:ios:563e4a83ccfd9738d6323a',
    messagingSenderId: '260233386063',
    projectId: 'avi-care',
    storageBucket: 'avi-care.firebasestorage.app',
    iosBundleId: 'com.example.aviCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC87_NBzLeMvm0FZTQPZjUJ-BYYOsbYzSo',
    appId: '1:260233386063:ios:563e4a83ccfd9738d6323a',
    messagingSenderId: '260233386063',
    projectId: 'avi-care',
    storageBucket: 'avi-care.firebasestorage.app',
    iosBundleId: 'com.example.aviCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADTQLAR7-Wtksfj0sPTx3oSvjBXkHcooA',
    appId: '1:260233386063:web:6d66f2e67c05207bd6323a',
    messagingSenderId: '260233386063',
    projectId: 'avi-care',
    authDomain: 'avi-care.firebaseapp.com',
    storageBucket: 'avi-care.firebasestorage.app',
  );
}
